packages:
  - main
  - renderer
  - shared

onlyBuiltDependencies:
  - '@fortawesome/fontawesome-common-types'
  - '@fortawesome/fontawesome-svg-core'
  - '@fortawesome/free-regular-svg-icons'
  - '@fortawesome/free-solid-svg-icons'
  - '@s-h-a-d-o-w/serenade-driver'
  - '@s-h-a-d-o-w/speech-recorder'
  - bufferutil
  - electron
  - electron-winstaller
  - esbuild
  - protobufjs
  - utf-8-validate
